app = 'swap-watcher-production'
primary_region = 'bos'
kill_signal = 'SIGINT'
kill_timeout = 10

[build]

[build.args]
  ENTRY_POINT_FILE_PATH='swap-watcher/dist/src/main.js'
  PACKAGE_NAME='@wiretap/swap-watcher'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory_mb = 512
  cpu_kind = 'shared'
  cpus = 1
