export enum RebalancesLogLabel {
  SET_FULL_ETH = 0,
  CREATED = 10,
  UPDATED = 20,
  TRIGGERED = 30,
  REBALANCE_RUNNING = 40,
  REBALANCE_COMPLETED = 50,
  WITHDRAW_REQUESTED = 60,

  ERROR = -10,
  ERROR_SET_FULL_ETH = -11,
  UPDATE_FAILED = -20,
  TRIGGER_FAILED = -30,
  REBALANCE_FAILED = -40,
  REBALANCE_NOT_COMPLETED = -50,
  REBALANCE_EXECUTION_FAILURE = -51,
  REBALANCE_BACKOFF_EXHAUSTED = -52,
  REBALANCE_RESULTED_FALSE = -53,
  WITHDRAW_REQUEST_FAILED = -60
}

export type RebalancesLogLabelNames = keyof typeof RebalancesLogLabel;
