export enum RebalancesLogLabel {
  SET_FULL_ETH = 0,
  CREATED = 10,
  UPDATED = 20,
  TRIGGERED = 30,
  TRIGGERED_VIA_TX = 31,
  REBALANCE_RUNNING = 40,
  TX_EXECUTION_RUNNING = 41,
  REBALANCE_COMPLETED = 50,
  TX_EXECUTION_COMPLETED = 51,
  WITHDRAW_REQUESTED = 60,

  ERROR = -10,
  ERROR_SET_FULL_ETH = -11,
  UPDATE_FAILED = -20,
  TRIGGER_FAILED = -30,
  TRIGGER_VIA_TX_FAILED = -31,
  REBALANCE_FAILED = -40,
  TX_EXECUTION_FAILED = -41,
  REBALANCE_NOT_COMPLETED = -50,
  REBALANCE_EXECUTION_FAILURE = -51,
  REBALANCE_BACKOFF_EXHAUSTED = -52,
  REBALANCE_RESULTED_FALSE = -53,
  TX_EXECUTION_NOT_COMPLETED = -54,
  TX_EXECUTION_RESULTED_FALSE = -55,
  TX_EXECUTION_BACKOFF_EXHAUSTED = -56,
  WITHDRAW_REQUEST_FAILED = -60
}

export type RebalancesLogLabelNames = keyof typeof RebalancesLogLabel;
