app = 'token-created-watcher-staging'
primary_region = 'bos'

[build]

[build.args]
  ENTRY_POINT_FILE_PATH='token-created-watcher/dist/src/main.js'
  PACKAGE_NAME='@wiretap/token-created-watcher'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory_mb = 512
  cpu_kind = 'shared'
  cpus = 1
